# -*- coding: utf-8 -*-
"""entities_near_phrases.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_vht5vBpVz2ZY93ID26ndSZ55s7yeOA
"""

"""
entities_near_phrases.ipynb

Goal:
- Load bib_interviewee_date_body.json
- Load and merge all batch_runs/gliner_by_entity*.json files
- Search transcript bodies for multiple target phrases
- Count which known entities appear near each phrase
"""

from google.colab import drive
drive.mount("/content/drive")

import os
import re
import json
import csv
from glob import glob
from bs4 import BeautifulSoup
from collections import Counter


BASE_DIR = "/content/drive/MyDrive/HDSSI_AIP"  # change if needed

TRANSCRIPTS_FILE = os.path.join(BASE_DIR, "bib_interviewee_date_body.json")
BATCH_RUNS_DIR = os.path.join(BASE_DIR, "batch_runs")

OUTPUT_DIR = os.path.join(BASE_DIR, "phrase_entity_results")
os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET_PHRASES = [
    "graduate student",
    "my father",
    "my mother",
    "my wife"
]

WINDOW_CHARS = 500

# Set to ["name"] if we only want people names, else None
ENTITY_TYPES_TO_KEEP = ["name"]
# ENTITY_TYPES_TO_KEEP = ["name"]

OUTPUT_JSON = os.path.join(OUTPUT_DIR, "entities_near_phrases.json")
OUTPUT_CSV = os.path.join(OUTPUT_DIR, "entities_near_phrases_summary.csv")


# helper functions

def clean_html(text):
    if not text:
        return ""
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text(" ", strip=True)


def normalize_space(text):
    return re.sub(r"\s+", " ", text).strip()


def safe_filename(text):
    return re.sub(r"[^a-zA-Z0-9_]+", "_", text.lower()).strip("_")


def make_entity_pattern(entity):
    escaped = re.escape(entity)
    return re.compile(rf"(?<!\w){escaped}(?!\w)", re.IGNORECASE)


def find_phrase_windows(text, phrase, window_chars=500):
    pattern = re.compile(re.escape(phrase), re.IGNORECASE)
    windows = []

    for match in pattern.finditer(text):
        start = max(0, match.start() - window_chars)
        end = min(len(text), match.end() + window_chars)

        windows.append({
            "phrase": phrase,
            "phrase_start": match.start(),
            "phrase_end": match.end(),
            "window_start": start,
            "window_end": end,
            "window_text": text[start:end]
        })

    return windows



print("Loading transcripts...")

with open(TRANSCRIPTS_FILE, "r", encoding="utf-8") as f:
    transcripts = json.load(f)

transcript_texts = {}

for t in transcripts:
    bib = str(t.get("field_bib_number", "")).strip()
    body = t.get("body", "")

    transcript_texts[bib] = {
        "interviewee": t.get("interviewee", ""),
        "interview_date": t.get("interview_date", ""),
        "text": normalize_space(clean_html(body))
    }

print(f"Loaded {len(transcript_texts)} transcripts.")


# load + consolidate entities

print("Loading GLiNER entity files...")

entity_files = sorted(glob(os.path.join(BATCH_RUNS_DIR, "gliner_by_entity*.json")))

print(f"Found {len(entity_files)} gliner_by_entity files.")

entities = {}

for path in entity_files:
    print("Reading:", os.path.basename(path))

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for item in data:
        entity = normalize_space(item.get("entity", ""))
        ent_type = item.get("type", "")

        if not entity:
            continue

        if ENTITY_TYPES_TO_KEEP is not None and ent_type not in ENTITY_TYPES_TO_KEEP:
            continue

        key = (entity.lower(), ent_type)

        if key not in entities:
            entities[key] = {
                "entity": entity,
                "type": ent_type,
                "gliner_total_count": 0,
                "counts_by_transcript": Counter()
            }

        entities[key]["gliner_total_count"] += item.get("total_count", 0)

        for bib, count in item.get("counts_by_transcript", {}).items():
            entities[key]["counts_by_transcript"][str(bib)] += count

print(f"Consolidated {len(entities)} unique entity/type pairs.")


# search phrases

all_results = {}

for phrase in TARGET_PHRASES:
    print(f"\nSearching phrase: {phrase!r}")

    phrase_results = {}

    for bib, meta in transcript_texts.items():
        text = meta["text"]
        windows = find_phrase_windows(text, phrase, WINDOW_CHARS)

        if not windows:
            continue

        for window in windows:
            window_text = window["window_text"]

            for key, ent in entities.items():
                entity = ent["entity"]

                # Only search entities that GLiNER found in this transcript
                if bib not in ent["counts_by_transcript"]:
                    continue

                pattern = make_entity_pattern(entity)
                matches = list(pattern.finditer(window_text))

                if not matches:
                    continue

                result_key = f"{entity}|||{ent['type']}"

                if result_key not in phrase_results:
                    phrase_results[result_key] = {
                        "entity": entity,
                        "type": ent["type"],
                        "near_phrase_count": 0,
                        "gliner_total_count": ent["gliner_total_count"],
                        "transcript_count": 0,
                        "counts_by_transcript": Counter(),
                        "examples": []
                    }

                phrase_results[result_key]["near_phrase_count"] += len(matches)
                phrase_results[result_key]["counts_by_transcript"][bib] += len(matches)

                if len(phrase_results[result_key]["examples"]) < 5:
                    phrase_results[result_key]["examples"].append({
                        "bib": bib,
                        "interviewee": meta["interviewee"],
                        "interview_date": meta["interview_date"],
                        "phrase": phrase,
                        "window_text": window_text
                    })

    final_phrase_results = []

    for item in phrase_results.values():
        item["counts_by_transcript"] = dict(item["counts_by_transcript"])
        item["transcript_count"] = len(item["counts_by_transcript"])
        final_phrase_results.append(item)

    final_phrase_results.sort(
        key=lambda x: (x["near_phrase_count"], x["transcript_count"]),
        reverse=True
    )

    all_results[phrase] = final_phrase_results

    print(f"Found {len(final_phrase_results)} entities near {phrase!r}.")


# save one combined json

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(all_results, f, indent=2, ensure_ascii=False)

print("\nSaved full JSON:", OUTPUT_JSON)


# save one combined CSV

with open(OUTPUT_CSV, "w", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(
        f,
        fieldnames=[
            "phrase",
            "entity",
            "type",
            "near_phrase_count",
            "transcript_count",
            "gliner_total_count",
            "counts_by_transcript"
        ]
    )

    writer.writeheader()

    for phrase, phrase_results in all_results.items():
        for item in phrase_results:
            writer.writerow({
                "phrase": phrase,
                "entity": item["entity"],
                "type": item["type"],
                "near_phrase_count": item["near_phrase_count"],
                "transcript_count": item["transcript_count"],
                "gliner_total_count": item["gliner_total_count"],
                "counts_by_transcript": json.dumps(
                    item["counts_by_transcript"],
                    ensure_ascii=False
                )
            })

print("Saved combined CSV:", OUTPUT_CSV)


# save one csv per phrase

for phrase, phrase_results in all_results.items():
    phrase_csv = os.path.join(
        OUTPUT_DIR,
        f"entities_near_{safe_filename(phrase)}.csv"
    )

    with open(phrase_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "entity",
                "type",
                "near_phrase_count",
                "transcript_count",
                "gliner_total_count",
                "counts_by_transcript"
            ]
        )

        writer.writeheader()

        for item in phrase_results:
            writer.writerow({
                "entity": item["entity"],
                "type": item["type"],
                "near_phrase_count": item["near_phrase_count"],
                "transcript_count": item["transcript_count"],
                "gliner_total_count": item["gliner_total_count"],
                "counts_by_transcript": json.dumps(
                    item["counts_by_transcript"],
                    ensure_ascii=False
                )
            })

print("Saved one CSV per phrase.")


# print top results

for phrase, phrase_results in all_results.items():
    print(f"\nTop entities near {phrase!r}:")
    for item in phrase_results[:10]:
        print(
            item["entity"],
            "| type:", item["type"],
            "| near phrase:", item["near_phrase_count"],
            "| transcripts:", item["transcript_count"]
        )